### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.neighbors._kd_tree'

### ISSUE THREAD

**Issue by SimonHensel** [svip-lab/PPGNet#24]
Hallo,
I know this might get overlooked since the repository is relatively old, but maybe someone has an idea what might be the solution to my problem.
Normally I use the pytorch/pytorch:0.4.1-cuda9-cudnn7-devel Docker environment  for my training of the PPGNet, which worked perfectly fine up until this week. Since then I get the following Error-message:
```console
Traceback (most recent call last):
  File "main.py", line 523, in <module>
    fire.Fire(LSDTrainer)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/opt/conda/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 360, in train
    self._train_epoch()
  File "main.py", line 211, in _train_epoch
    for i, batch in enumerate(data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/simon/PPGNet/data/sist_line.py", line 24, in __getitem__
    lg = LineGraph().load(os.path.join(self.data_root, self.img[item][:-4] + ".lg"))
  File "/home/simon/PPGNet/data/line_graph.py", line 31, in load
    data = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.neighbors._kd_tree'
```
I use the recommended packages, as it can be seen in the following pip list:
```console
Package          Version
---------------- -----------
asn1crypto       0.24.0
backcall         0.1.0
beautifulsoup4   4.6.0
certifi          2018.4.16
cffi             1.11.5
chardet          3.0.4
conda            4.5.8
conda-build      3.12.0
cryptography     2.2.2
Cython           0.29.32
decorator        4.3.0
filelock         3.0.4
fire             0.4.0
glob2            0.6
idna             2.6
ipython          6.4.0
ipython_genutils 0.2.0
jedi             0.12.1
Jinja2           2.10
llvmlite         0.36.0
lxml             4.9.1
MarkupSafe       1.0
mkl-fft          1.0.4
mkl-random       1.0.1
numba            0.53.1
numpy            1.19.5
olefile          0.45.1
opencv-python    4.6.0.66
parso            0.3.1
pexpect          4.6.0
pickleshare      0.7.4
Pillow           5.2.0
pip              21.3.1
pkginfo          1.4.2
prompt-toolkit   1.0.15
protobuf         3.19.6
psutil           5.4.6
ptyprocess       0.6.0
pycosat          0.6.3
pycparser        2.18
Pygments         2.2.0
pyOpenSSL        18.0.0
PySocks          1.6.8
PyYAML           3.13
requests         2.18.4
ruamel_yaml      0.15.37
scikit-learn     0.19.2
scipy            1.1.0
setuptools       39.2.0
Shapely          1.8.5.post1
simplegeneric    0.8.1
six              1.11.0
tensorboardX     2.5.1
termcolor        1.1.0
torch            0.4.1
torchvision      0.2.1
traitlets        4.3.2
triangle         20220202
urllib3          1.22
wcwidth          0.1.7
wheel            0.31.1
```

Currently I don't know a solution. I tried conda environments instead of docker, no success. Fresh installation on a different system, no success. Newer version of torch, torchvision, scikit-learn, no success. 

But it seems like I am not the only one with the problem, since here (https://githubhelp.com/qingyonghu/sensaturban/issues/18) the same issue is also discussed without a solution.

**Comment by SimonHensel** [comment]
OK, I found the issue. For anyone else stumbling across this. It seems to be mandatory to use the same scikit-learn version, when the training data is created using pickle. When I created my training data in the same docker environment everything worked fine again.
