### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by glushakviktor** [svip-lab/PPGNet#7]
Hello, in root directory i did "git lfs pull", and my files in path "ckpt/backbone/" 
decoder_epoch_20.pth has 162.5Mb
encoder_epoch_20.pth has 95Mb

When I run ./train.sh I have:

Loading weights for net_encoder @ ckpt/backbone/encoder_epoch_20.pth
Loading weights for net_decoder @ ckpt/backbone/decoder_epoch_20.pth
Traceback (most recent call last):
  File "main.py", line 521, in <module>
    fire.Fire(LSDTrainer)
  File "/home/user/anaconda3/envs/ppgnet/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/user/anaconda3/envs/ppgnet/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/user/anaconda3/envs/ppgnet/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 121, in __init__
    pin_memory=True
  File "/home/user/anaconda3/envs/ppgnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/user/anaconda3/envs/ppgnet/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))

ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by rayryeng** [comment]
It sounds like you didn't download and extract the training data properly.  The link is provided on the README.  Did you download the dataset uncompress the data (it's a 7zipped archived file, followed by a combined TAR+GZIP archive), then change the `--data-root` flag in the `train.sh` script to be where you downloaded the data?

**Comment by allankevinrichie** [comment]
I think @rayryeng is right. I added an assertion in the `main.py` script to provide more friendly error messages about this problem.
