### ISSUE TITLE
can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by glushakviktor** [svip-lab/PPGNet#8]
Hello! I have gtx1050mobile with CUDA on my laptop. My ./train.sh contains:

python main.py \
--exp-name line_weighted_wo_focal_junc --backbone resnet50 \
--backbone-kwargs '{"encoder_weights": "ckpt/backbone/encoder_epoch_20.pth", "decoder_weights": "ckpt/backbone/decoder_epoch_20.pth"}' \
--dim-embedding 256 --junction-pooling-threshold 0.2 \
--junc-pooling-size 64 --attention-sigma 1.5 --block-inference-size 2 \
--data-root ./data/indoorDist/ --junc-sigma 3 \
--batch-size 2 --gpus 0,1,2,3 --num-workers 0 --resume-epoch latest \
--is-train-junc True --is-train-adj True \
--vis-junc-th 0.1 --vis-line-th 0.1 \
    - train --end-epoch 9 --solver SGD --lr 0.2 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 5. \
    - train --end-epoch 15 --solver SGD --lr 0.02 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 10. \
    - train --end-epoch 30 --solver SGD --lr 0.002 --weight-decay 5e-4 --lambda-heatmap 1. --lambda-adj 10. \
    - end

After run I get:

Loading weights for net_encoder @ ckpt/backbone/encoder_epoch_20.pth
Loading weights for net_decoder @ ckpt/backbone/decoder_epoch_20.pth
find 481 jucntions.
Traceback (most recent call last):
  File "main.py", line 548, in <module>
    fire.Fire(LSDTrainer)
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "main.py", line 377, in train
    self._train_epoch()
  File "main.py", line 238, in _train_epoch
    junctions_gt
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Загрузки/PPGNet/PPGNet/models/lsd.py", line 202, in forward
    junc_hm, junc_coords = self.junc_infer(feat)
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/Загрузки/PPGNet/PPGNet/models/graph.py", line 42, in forward
    coord = coord[ind[:self.max_juncs]]
  File "/home/user/.virtualenvs/PPGNet/lib/python3.6/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by rayryeng** [comment]
This is because of your PyTorch version.   You need to specifically install PyTorch 0.4.1.  Using `pip`, please do: `pip install torch==0.4.1`.  More recent versions of Torch no longer support Tensor slicing in device memory and require the Tensor to be copied to host memory first.

**Comment by rayryeng** [comment]
@allankevinrichie I would suggest having a `requirements.txt` file or `Pipfile/Pipfile.lock` that specifically lists the dependencies with the exact versions they need and direct users to install the packages with this file.  Obviously, they should use this in a new virtual environment / `pipenv` so it doesn't pollute their main Python environment.

**Comment by magic428** [comment]
Hi @rayryeng,

Just add a line before File "/home/user/Загрузки/PPGNet/PPGNet/models/graph.py", line 42:  

`ind = ind.cpu() `
`coord = coord[ind[:self.max_juncs]]`

**Comment by rayryeng** [comment]
@magic428 That works!  Is this the only change you needed to make?  I should make an appropriate PR.

**Comment by magic428** [comment]
yeap, the author @allankevinrichie  has done some push request to fix some bugs with several incompatibility.

**Comment by allankevinrichie** [comment]
It seems that some PyTorch versions do the conversion automatically while others don't. I have added a line as suggested by @magic428 to do the conversion explicitly in https://github.com/svip-lab/PPGNet/commit/ae55d6729964023b3c4f10543a2161d41165fb96. Thank you both @rayryeng @rayryeng  for your interest in our work!
